diagnosis

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -34,24 +34,24 @@ jobs:
             - name: Set environment variables
               run: |
                 echo "JWT_SECRET=testSecret" >> .env
-                echo "DB_URL=mongodb://database:27017/dev" >> .env
-                echo "TEST_DB_URL=mongodb://localhost:27017/test" >> .env
-            - name: Build and start app
-              run: docker-compose --env-file .env -f docker-compose.yml up -d
-            - name: Wait for test database to be ready
-              run: |
-                retries=5
-                count=0
-                until docker exec mongo_db_community mongosh mongodb://database:27017/dev --quiet|| [ $count -ge $retries ]; do
-                  echo "Waiting for test_db to be ready...Attempt $((count + 1))/$retries"
-                  sleep 5
-                  count=$((count + 1))
-                done
-                if [ $count -ge $retries ]; then
-                  echo "The test db did not start in time, exiting..."
-                  exit 1
-                echo "Connection test successful"
-                fi
+                echo "DB_URL=mongodb://0.0.0.0:27017/dev" >> .env
+                echo "TEST_DB_URL=mongodb://0.0.0.0:27017/test" >> .env
+            # - name: Build and start app
+            #   run: docker-compose --env-file .env -f docker-compose.yml up -d
+            # - name: Wait for test database to be ready
+            #   run: |
+            #     retries=5
+            #     count=0
+            #     until docker exec mongo_db_community mongosh mongodb://database:27017/dev --quiet|| [ $count -ge $retries ]; do
+            #       echo "Waiting for test_db to be ready...Attempt $((count + 1))/$retries"
+            #       sleep 5
+            #       count=$((count + 1))
+            #     done
+            #     if [ $count -ge $retries ]; then
+            #       echo "The test db did not start in time, exiting..."
+            #       exit 1
+            #     echo "Connection test successful"
+            #     fi
             - name: Start mongodb service
               uses: supercharge/mongodb-github-action@1.12.0
               with:
